download.file("https://archive.ics.uci.edu/ml/machine-learning-databases/00235/household_power_consumption.zip", destfile = "power.csv", mode = "wb")
columnnames <- c( "Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1",  "Sub_metering_2", "Sub_metering_3")
file <- read.table(unzip("power.csv"), col.names = columnnames, sep = ";", skip = 66637, nrow = 2880, header = FALSE, colClasses = c("character", "character", rep("numeric",7)))
library(dplyr)
library(lubridate)
file2 <- mutate (file, DateTime = paste(Date, Time, sep = " "))
file2$DateTime <- dmy_hms(file2$DateTime)
png (filename = "plot3.png", width = 480, height = 480, pointsize = 12, bg = "white")
plot(file2$DateTime, file2$Sub_metering_1, type = "l", ylab ="Energy sub metering", xlab = " ")
points(file2$DateTime, file2$Sub_metering_2, col = "red", type = "l")
points(file2$DateTime, file2$Sub_metering_3, col = "blue", type = "l")
legend("topright", lty = 1, lwd = 3, col = c("black", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()