columnnames <- c( "Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1",  "Sub_metering_2", "Sub_metering_3")
file <- read.table("household_power_consumption.txt", col.names = columnnames, sep = ";", skip = 66637, nrow = 2880, header = FALSE, colClasses = c("character", "character", rep("numeric",7)))
library(dplyr)
library(lubridate)
file2 <- mutate (file, DateTime = paste(Date, Time, sep = " "))
file2$DateTime <- dmy_hms(file2$DateTime)
plot(file2$DateTime, file2$Global_active_power, type = "l", ylab ="Global Active Power (kilowatts)", xlab = " ")
dev.copy(png, filename = "plot2.png", width = 480, height = 480, pointsize = 12, bg = "white")
dev.off()